Sample_Publisher: Added a Sample Publisher.
open-edge-insights/uwc pull request #10
Opened 2021-08-12 15:10 UTC by aditisa1

Added a python sample publisher for data persist.

Signed-off-by: aditi saxena <aditi.saxena@intel.com>

2021-08-12 16:33 UTC, aditisa1 commented
@vanidesai can you please review the MR

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/Dockerfile
> +# Copyright (c) 2020 Intel Corporation.
lets update the year. Lets add the same license as in all other files we have in open source.

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/README.md
> +# Python Publisher
Lets also mention about the sample JSON payload that we are writing.

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/README.md
> +This is a sample python publisher which is used to test the data persistant feature by publishing a dummy json payload on the msg bus which is then stored on influx db.
Lets explicitly call out that this sample app just demonstrates how to write a sample data into the influx database without getting involved with any of the UWC services. So, lets rephrase this statement "used to test the data persistant feature".

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/backup
> +{
I think this file is not needed. we have config.json already.

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/config.json
> +                "Name": "echo_service",
I know we saw today that removing this server had some issues wrt EII config manager complaining. But re-thinking on it -- this might confuse the users as to why is server used. So, check with COnfigManager EII owners. Lakshmi if server can be removed & keep only publisher.

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/docker-compose.yml
> +  etcd_PythonPublisher_cert:
lets test in prod mode once before merge.

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/main.py
> +# Copyright (c) 2020 Intel Corporation.
lets have same license text as in other UWC files. (year to be updated).

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/publisher.py
> +# Copyright (c) 2020 Intel Corporation.
same comment as above "license text"

2021-08-12 17:33 UTC, nagdeepgk commented on Sample_Publisher/server.py
> +# Copyright (c) 2020 Intel Corporation.
base don the above comment, lets check with Cfgmgr EII owners (Lakshmi)  if EII config manager permits removal of just server entry by just keeping publisher  in this file

2021-08-13 06:50 UTC, vanidesai requested changes

2021-08-13 06:50 UTC, vanidesai commented on Sample_Publisher/README.md
> +# Python Publisher
The folder name should be renamed if the publisher only for the database. I would rename it "Sample_DB_Publisher

2021-08-13 06:50 UTC, vanidesai commented on Sample_Publisher/server.py
> +def start_server():
why do you need echo service file?

2021-08-13 07:14 UTC, arunkk-intel commented
Do we need a separate sample publisher? Why can't we use https://github.com/open-edge-insights/eii-tools/tree/master/EmbPublisher

2021-08-13 07:43 UTC, aditisa1 commented on Sample_Publisher/server.py
> +def start_server():
### In EII sample python publisher it was there 
i have removed it from our use case

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/Dockerfile
> +#
I see we are following mix of '-' and '_' for naming folder names in uwc repo, we can stick with one when it comes it naming apps. Eg: SampleDBPublisher can be the folder name

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/Dockerfile
> +# Dockerfile for Python_sample_publisher
Here I see diff name to that in fodler

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/Dockerfile
> +RUN mv ./*.py $ARTIFACTS
You can combine above 2 statements into one like `COPY ./*.py $ARTIFACTS`

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/Dockerfile
> +    rm -rf /var/lib/apt/lists/*
If we are using ubuntu:20.04 as the base image, then this instruction can be simplified like it's done at https://github.com/open-edge-insights/eii-factoryctrl/blob/master/Dockerfile#L45 as ubuntu:20.04 docker image comes with python 3.8 by default

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/README.md
> +# Sample DB Publisher
Should this be changed to Sample python publisher

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/README.md
> +This is a sample python publisher which is to writes sample data into the influx database without getting involved with any of the UWC services.
`which is to` can be replaced with `which`

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/README.md
> +   * if the string is to be added in sample payload key then please add key in [Telegraf_devmode.conf](../../Telegraf/config/Telegraf/Telegraf_devmode.conf) json_string_fields section.
Caps If

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/docker-compose.yml
> +version: '3.6'
Copyright header missing

2021-08-13 09:09 UTC, vkb1 commented on Sample_DB_Publisher/publisher.py
> +"""EII Message Bus publisher example
Should this be renamed?

2021-08-13 09:09 UTC, vkb1 commented on build_scripts/03_Build_Run_UWC.sh
> +    docker ps -q --filter "name=ia_influxdbconnector" | grep -q . && echo "ia_influxdbconnector"
What's the intention of these commands?

2021-08-13 09:09 UTC, vkb1 commented on uwc_recipes/uwc-pipeline-sample-publisher.yml
> +- uwc/Sample_Publisher
Folder name seems to be wrong here

2021-08-13 11:01 UTC, aditisa1 commented
@arunkk-intel 
we were looking for a python publisher so we selected the below one 
https://gitlab.devtools.intel.com/Indu/edge-insights-industrial/eii-samples/-/tree/master/python_sample_app/publisher
and customized json and code according to need

2021-08-13 11:14 UTC, vkb1 approved these changes
Hey @aditisa1 , You can update the commit title and push. Also, let's avoid force pushing as there isn't a best way to see the changes introduced in latest push when we do force push.

2021-08-16 04:20 UTC, arunkk-intel commented
> @arunkk-intel
> we were looking for a python publisher so we selected the below one
> https://gitlab.devtools.intel.com/Indu/edge-insights-industrial/eii-samples/-/tree/master/python_sample_app/publisher
> and customized json and code according to need

2021-08-16 04:40 UTC, arunkk-intel commented
> > @arunkk-intel
> > we were looking for a python publisher so we selected the below one
> > https://gitlab.devtools.intel.com/Indu/edge-insights-industrial/eii-samples/-/tree/master/python_sample_app/publisher
> > and customized json and code according to need

@aditisa1 we can use the python publisher, but why duplicate the code again? My ask was to try use an existing publisher if your requirement is only to publish data into the message bus. The EmbPublisher tool can also take data file json to publish it over bus. If we find that there is more features needed for it, we can enable it there as well. Lets discuss on this.

2021-08-16 05:25 UTC, aditisa1 commented
> > > @arunkk-intel
> > > we were looking for a python publisher so we selected the below one
> > > https://gitlab.devtools.intel.com/Indu/edge-insights-industrial/eii-samples/-/tree/master/python_sample_app/publisher
> > > and customized json and code according to need
> 
> @aditisa1 we can use the python publisher, but why duplicate the code again? My ask was to try use an existing publisher if your requirement is only to publish data into the message bus. The EmbPublisher tool can also take data file json to publish it over bus. If we find that there is more features needed for it, we can enable it there as well. Lets discuss on this.

@arunkk-intel We have modified the publisher to UWC requirements.So for that reason, we are keeping it in UWC

2021-08-16 07:07 UTC, vanidesai commented on build_scripts/03_Build_Run_UWC.sh
> +    docker ps -q --filter "name=ia_influxdbconnector" | grep -q . && echo "ia_influxdbconnector"
[Yesterday 11:30 PM] Saxena, Aditi
    regarding above one
that is needed as in 08 script 
we are only running influx telegraf  ETCDUI broker and sample 
(1 liked)​[Yesterday 11:31 PM] Saxena, Aditi
    so extra mqtt container names were getting printed so to avoid the confusion

2021-08-16 07:08 UTC, vanidesai commented on SampleDBPublisher/config.json
> +        "loop_interval": "1"
can you add comment here? Is loop interval in seconds, milliseconds?

2021-08-16 07:09 UTC, vanidesai approved these changes
I approved PR. You need to add a comment in the config.json for the loop interval

2021-08-16 07:30 UTC, nagdeepgk approved these changes

2021-08-25 05:24 UTC, nagdeepgk commented
Closing this PR, as there was another PR for the sample DB publisher app. https://github.com/open-edge-insights/uwc/pull/13 (already merged).
This was due to a review comment from Arun to utilize the existing publisher app (from EII's tools repo) instead of duplicating code.

2021-08-25 05:24 UTC, closed without merging