Enable data persistence feature in UWC (Integrate Telegraf/InfluxDBConnector micro-services with UWC)
open-edge-insights/uwc pull request #11
Opened 2021-08-12 20:24 UTC by nagdeepgk

uwc : Integrate Telegraf/InfluxDBConnector micro-services with UWC

        1. Add additional use cases "5","6","7" for enabling time series containers (telegraf/InfluxDBConnector) in various combination with KPI-app/Sparkplug.
        2. ReadMe updated for data-persistence feature.
        3. 01 script updated to override  EII Telegraf/InfluxDBconnector config files with UWC specific data persistence related config files.
        4. Added more recipe files for more usecases of data persistence.
        5. Stored UWC specific custom config files for Telegraf and influxdbconnector in UWC specific folder eii_config.
        6. Updated retention policy.

    Signed-off-by: nagdeepgk <nagdeep.gk@intel.com>

2021-08-13 07:05 UTC, aditisa1 commented on build_scripts/02_provision_UWC.sh
> +        echo "5) Basic UWC micro-services with Time series micro-services (Telegraf & InfluxDBConnector)"
I guess 
echo message for 6 and 7 is missed

2021-08-13 07:12 UTC, arunkk-intel commented on README.md
> +  Data is stored in DB if the value is true and not stored if teh value is false. Also if teh field "dataPersist" is skipped, then the the datapoint is not stored.
typo teh -> the

2021-08-13 07:12 UTC, arunkk-intel commented on README.md
> +  Note that any string value that is present in the JSON response payload which is publiched to telegraf needs to have all the string fields listed in the telegraf configuration file for enabling the
Typo published

2021-08-13 07:12 UTC, arunkk-intel commented on README.md
> +  Note that any string value that is present in the JSON response payload which is publiched to telegraf needs to have all the string fields listed in the telegraf configuration file for enabling the
Also the sentence is long and difficult to understand. Consider splitting and rewording.

2021-08-13 07:12 UTC, arunkk-intel commented on README.md
> +  The default retention period is set to 24 hours. Although the field "retention" in config.json is et to 23 hours, it includes a default shard duration of 1 hour which totally accounts to 24 hours o
The default value in the above file is 1h30m5s. This can cause confusion while reading this line.

2021-08-13 07:12 UTC, arunkk-intel commented on README.md
> +  Refer influxDB documentation for more details.
Better provide a link for Influx retention policy here.

2021-08-13 07:21 UTC, joydipdx commented on eii_configs/service_specific_cfgs/Telegraf/Telegraf.conf
> +   [outputs.influxdb.tagpass]
We need to keep this changes at the end of plugin:
# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  # urls = ["udp://127.0.0.1:8089"]
   urls = ["https://$INFLUX_SERVER:$INFLUXDB_PORT"]
   metric_batch_size = 500
   flush_interval = "10s"
   metric_buffer_limit = 50000

  ## The target database for metrics; will be created as needed.
   database = "$INFLUXDB_DBNAME"
  ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
  ## Telegraf with a user without permissions to create databases or when the
  ## database already exists.
   skip_database_creation = true


  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.  Only takes effect when using HTTP.
  # retention_policy = ""

  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all".
  ## Only takes effect when using HTTP.
  # write_consistency = "any"

  ## Timeout for HTTP messages.
  # timeout = "5s"

  ## HTTP Basic Auth
   username = "$INFLUXDB_USERNAME"
   password = "$INFLUXDB_PASSWORD"
  ## HTTP User-Agent
  # user_agent = "telegraf"

  ## UDP payload size is the maximum packet size to send.
  # udp_payload = 512

  ## Optional TLS Config for use on HTTP connections.
   tls_ca = "/tmp/ca_certificate.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  insecure_skip_verify = false

  ## HTTP Proxy override, if unset values the standard proxy environment
  ## variables are consulted to determine which proxy, if any, should be used.
  # http_proxy = "http://corporate.proxy:3128"

  ## Additional HTTP headers
  # http_headers = {"X-Special-Header" = "Special-Value"}

  ## HTTP Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
  # content_encoding = "identity"

  ## When true, Telegraf will output unsigned integers as unsigned values,
  ## i.e.: "42u".  You will need a version of InfluxDB supporting unsigned
  ## integer values.  Enabling this option will result in field type errors if
  ## existing data has been written.
  # influx_uint_support = false
  tagexclude = ["dataPersist"]

  [outputs.influxdb.tagpass]
   dataPersist = [ "true" ]

2021-08-13 07:42 UTC, vanidesai requested changes
Telegraf conf is not configured as per UWC data persistence design. Requires rework

2021-08-13 07:42 UTC, vanidesai commented on uwc_recipes/uwc-pipeline-basic-kpiapp-sparkplug-timeseries.yml
> +- uwc/kpi-tactic
KPI App is not required. This is production receipe

2021-08-13 07:42 UTC, vanidesai commented on eii_configs/service_specific_cfgs/Telegraf/Telegraf.conf
> +# Synchronously processing the messages
There is a lot of commented EII code into the conf file. Please remove all EII commented code. It is difficult view this file with so much commented code

2021-08-13 07:42 UTC, vanidesai commented on eii_configs/service_specific_cfgs/Telegraf/Telegraf.conf
> +  "dataPersist"
Please refer data persistence design powerpoint. I don't see a tag set configured here. The tags are used for indexing in addition to default indexing based on time. Refer each message type (Polling, ReadResponse and write response etc) and add tag set as per design. 
Here is one example for polling
Flow, wellhead=PL0,status=Good realtime=1,value=“0x01”,scaledValue=1, app_seq=1233

2021-08-13 07:52 UTC, joydipdx commented on README.md
> +  The default retention period is set to 24 hours. Although the field "retention" in config.json is et to 23 hours, it includes a default shard duration of 1 hour which totally accounts to 24 hours o
I think we do not need to keep retention policy is is set to 24 hours, Better to keep retention policy as 23 hour for shard group. Because all the data in shard group will not be present for full 24 hour.

2021-08-13 09:13 UTC, vkb1 commented on README.md
> +  The default retention period is set to 24 hours. Although the field "retention" in config.json is et to 23 hours, it includes a default shard duration of 1 hour which totally accounts to 24 hours o
+1. Few typos like et, shard

2021-08-13 09:13 UTC, vkb1 commented on README.md
> +  Refer influxDB documentation for more details.
+1

2021-08-13 09:13 UTC, vkb1 commented on build_scripts/02_provision_UWC.sh
> +        echo "5) Basic UWC micro-services with Time series micro-services (Telegraf & InfluxDBConnector)"
+1

2021-08-13 09:13 UTC, vkb1 commented on eii_configs/InfluxDBConnector.json
> +                "PublisherAppName": "VideoAnalytics",
Do we really need this subscription as UWC is a timeseries usecase?

2021-08-13 14:01 UTC, nagdeepgk commented on uwc_recipes/uwc-pipeline-basic-kpiapp-sparkplug-timeseries.yml
> +- uwc/kpi-tactic
sure, will remove KPI app from this recipe 7. Have a separate recipe for KPI-app itself along with minimal containers (use-case 6).

2021-08-13 14:03 UTC, nagdeepgk commented on build_scripts/02_provision_UWC.sh
> +                python3 builder.py -f ../uwc/uwc_recipes/uwc-pipeline-basic-kpiapp-sparkplug-timeseries.yml
sure modified.

2021-08-13 14:07 UTC, nagdeepgk commented on eii_configs/service_specific_cfgs/Telegraf/Telegraf.conf
> +# Synchronously processing the messages
The commented code is not from EII. INstead it's the default file taken from open source Telegraf github https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf. 

Uncommented/edited only those fields in this which we need.

2021-08-13 14:18 UTC, nagdeepgk commented on eii_configs/service_specific_cfgs/Telegraf/Telegraf.conf
> +  "dataPersist"
I wasn't aware of this tag set requirement for each msg type (polling, wrresponse, readResponse), as I wasn't involved in any of the earlier conversations/emails wrt this data persistence mtgs/emails. I was told only about this dataPersist flag based filtering of msgs and not for msg types. 

Hence, now post this comment I'm knowing about this & based on this I've added the other keys "wellhead, realtime & status" into the tag_keys as a tag set based on which we can do filtering. Changes updated in this PR branch. 
But this tag-set is common for all msg types.
Can you plz check this if this is what we needed.

2021-08-13 14:26 UTC, nagdeepgk commented on README.md
> +  The response received in JSON format is converted to metrices inside Telegraf micro service before passing the data to InfluxDB for storage.
typo corrected. No not bullet points.

2021-08-13 14:44 UTC, nagdeepgk commented on eii_configs/InfluxDBConnector.json
> +                "PublisherAppName": "VideoAnalytics",
Need to check that if its possible to have a config.json without the subscription ? Does EII new config mgr allow it ?

2021-08-13 14:46 UTC, nagdeepgk commented on eii_configs/InfluxDBConnector.json
> +                "PublisherAppName": "VideoAnalytics",
wrt https://github.com/open-edge-insights/uwc/pull/11#discussion_r688365166: "shard" is the right spelling. https://www.influxdata.com/blog/influxdb-shards-retention-policies/

2021-08-13 14:49 UTC, nagdeepgk commented on eii_configs/service_specific_cfgs/Telegraf/Telegraf.conf
> +   [outputs.influxdb.tagpass]
done

2021-08-13 14:49 UTC, nagdeepgk commented on README.md
> +  Refer influxDB documentation for more details.
done

2021-08-13 14:51 UTC, nagdeepgk commented on README.md
> +  The default retention period is set to 24 hours. Although the field "retention" in config.json is et to 23 hours, it includes a default shard duration of 1 hour which totally accounts to 24 hours o
A clarification: the default value is 1.5 hours in EII's influxDB's config.json. However, here we have maintained UWC's specific copied for config.json's whereever needed in uwc/eii_configs. Had to maintain a separate version for uwc only for this retention policy change, else i could have re-used same eii's file.

2021-08-13 14:51 UTC, nagdeepgk commented on README.md
> +  Note that any string value that is present in the JSON response payload which is publiched to telegraf needs to have all the string fields listed in the telegraf configuration file for enabling the
done

2021-08-13 14:52 UTC, nagdeepgk commented on README.md
> +  Data is stored in DB if the value is true and not stored if teh value is false. Also if teh field "dataPersist" is skipped, then the the datapoint is not stored.
done

2021-08-13 14:53 UTC, nagdeepgk commented on README.md
> +  The default retention period is set to 24 hours. Although the field "retention" in config.json is et to 23 hours, it includes a default shard duration of 1 hour which totally accounts to 24 hours o
yes in influx DB's config.json I've kept retention policy as 23 hrs only.

2021-08-16 06:01 UTC, vanidesai reviewed
Telegraf conf is not updated as per review comments

2021-08-16 06:09 UTC, vanidesai approved these changes

2021-08-16 10:39 UTC, vkb1 approved these changes

2021-08-16 10:45 UTC, joydipdx approved these changes

2021-08-16 11:45 UTC, merged