uwc : Changes for multi build.
open-edge-insights/uwc pull request #34
Opened 2021-11-15 07:37 UTC by aditisa1

Changed the runtime image for containers.

Signed-off-by: aditisa1 <aditi.saxena@intel.com>

2021-11-17 06:58 UTC, nagdeepgk commented
Changes look fine. However, I'd like to get the reviews from @vkb1  and @Kevin-Midkiff  wrt this multi-stage build changes.

2021-11-17 07:07 UTC, nagdeepgk commented on MQTT/docker-compose.yml
> +    image: ${DOCKER_REGISTRY}openedgeinsights/mqtt_container:${EII_VERSION}
@aditisa1 Curious as to why we need this change in "image:" section i.e. prefixing with "openedgeinsights"? I think its a common think you have done in all dockerfiles.

2021-11-17 07:07 UTC, nagdeepgk commented on kpi-tactic/Dockerfile
> +COPY --from=uwc_common /usr/local/lib ${APP_WORK_DIR}
Might be the previous line "COPY --from=uwc_common $CMAKE_INSTALL_PREFIX/lib  ${APP_WORK_DIR}" 
has to be removed ? Missed to remove or was it intentional ? I see its removed in other dockerfiles.

Also i want to understand the intention behind this new addition line.

2021-11-17 07:12 UTC, nagdeepgk commented on mqtt-bridge/Dockerfile
> +COPY --from=uwc_common /usr/local/lib/ ${APP_WORK_DIR}
same comment as in https://github.com/open-edge-insights/uwc/pull/34#discussion_r750946802

2021-11-17 07:12 UTC, nagdeepgk commented on uwc_common/Dockerfile.common
> +
minor: additional line can be removed.

2021-11-17 07:12 UTC, nagdeepgk commented on uwc_common/docker-compose.yml
> +          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
@vkb1 This movement into args section - is it fine ? Seems like it was removed from env to args section.

2021-11-22 09:31 UTC, aditisa1 commented on MQTT/docker-compose.yml
> +    image: ${DOCKER_REGISTRY}openedgeinsights/mqtt_container:${EII_VERSION}
Added openedgeinsights as all the open-source images has the same 
it basically represents the docker hub repo 
https://hub.docker.com/u/openedgeinsights

2021-11-22 09:32 UTC, aditisa1 commented on uwc_common/docker-compose.yml
> +          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
referred following docker-compose file for this , it has the same thing 

https://gitlab.devtools.intel.com/Indu/edge-insights-industrial/ts-telegraf/-/blob/master/docker-compose.yml

2021-11-22 09:33 UTC, aditisa1 commented on kpi-tactic/Dockerfile
> +COPY --from=uwc_common /usr/local/lib ${APP_WORK_DIR}
There are certain libs which are present in ia_common(uwc_common is using the final images as ia_common) /usr/local/lib and were not getting copied so added the above line

2021-11-23 06:31 UTC, vkb1 commented on MQTT/Dockerfile
>  FROM eiibase
This can be removed

2021-11-23 06:31 UTC, vkb1 commented on kpi-tactic/Dockerfile
> +COPY --from=uwc_common /usr/local/lib ${APP_WORK_DIR}
Let's undo this change, it's good to use CMAKE_INSTALL_PREFIX

2021-11-23 06:31 UTC, vkb1 commented on uwc_common/Dockerfile.common
> +FROM ia_common:$EII_VERSION
Minor, the trailing space can be removed

2021-11-23 07:03 UTC, aditisa1 commented on kpi-tactic/Dockerfile
> +COPY --from=uwc_common /usr/local/lib ${APP_WORK_DIR}
I tried with CMAKE_INSTALL_PREFIX but there are few libs that are missing in this, that is why I had to use /usr/local/lib which has all the libs generated in build stages by other containers mostly uwc_common

2021-11-24 09:30 UTC, aditisa1 commented on MQTT/Dockerfile
>  FROM eiibase
it is being used in line number 29 i.e FROM ubuntu:$UBUNTU_IMAGE_VERSION as runtime

2021-11-25 05:21 UTC, nagdeepgk commented on MQTT/docker-compose.yml
> +    image: ${DOCKER_REGISTRY}openedgeinsights/mqtt_container:${EII_VERSION}
@aditisa1 If you can plz give clarity for above comment ?

2021-11-25 05:28 UTC, aditisa1 commented on MQTT/docker-compose.yml
> +    image: ${DOCKER_REGISTRY}openedgeinsights/mqtt_container:${EII_VERSION}
openedgeinsights refers to the open-source docker hub 

all images here are like that 
https://hub.docker.com/u/openedgeinsights

2021-11-25 11:08 UTC, vats-in commented on build_scripts/03_Build_Run_UWC.sh
> +        test_1=`grep "ia_telegraf" "docker-compose-build.yml"`
what is test_1 and test_2. Should use meaningful names for variables.

2021-11-25 11:24 UTC, aditisa1 commented on build_scripts/03_Build_Run_UWC.sh
> +        test_1=`grep "ia_telegraf" "docker-compose-build.yml"`
those are just temporary variables created for storing grep results for testing 
so named the test

2021-11-25 18:40 UTC, nagdeepgk commented on build_scripts/02_provision_UWC.sh
> +    pre_build_images  "$pre_build"
we need to give in Readme & UG on how to call the 02 script for non-interactive mode.

2021-11-25 18:40 UTC, nagdeepgk commented on build_scripts/02_provision_UWC.sh
>  if [ -z "$1" ]; then
I don't think this condition would suffice to make a decision that it is an interactive mode.
What if user gives set_mode & configure_usecase and doesn't give the pre-built flag ? Our state logic should be able to handle such scenarios. However, if we are not supporting these hybrid scenarios, lets clearly call out in our readme/UG. Then can create a follow up story to introduce this hybrid logic later.

2021-11-25 18:40 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +        echo "Using pre_build images for building"
re-phrase - "Using pre_build images for building" -> "Using pre_build images"

2021-11-25 18:40 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +        if [ ! -z "$test_1" ]; then
Lets add comments at each if / else as to what is it doing.

2021-11-25 18:40 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +                docker-compose -f docker-compose-build.yml build ia_eiibase ia_common ia_telegraf emb_publisher
I think we missed adding influxDb. As I know even InfluxDB is not pre-build (just like telegraf) right ? Also do we need to mention the base images too explicitly ?

2021-11-25 18:40 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +                docker-compose -f docker-compose-build.yml build ia_eiibase ia_common ia_telegraf
I think we missed adding influxDb. As I know even InfluxDB is not pre-build (just like telegraf) right ? Also do we need to mention the base images too explicitly ?

2021-11-25 18:40 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +    rm setenv
I understand you are removing this as we don't need it any more. From from user point of view, if the user chooses to run 03 on a a different terminal (which will not have setenv sourced), then user will be mandated to everytime run 02 and then 03. So, I'd suggest to keep this file. And add the logic to remove it in 04 script.

2021-11-25 19:05 UTC, nagdeepgk commented
@aditisa1 : Few generic comments:
1. Can you please give a note on the size of docker images we reduced by doing this multi-stage migration ? Can run docker images on current ToT master code & then also run the same command on this code, which will give a delta of the size reduction we achieved ? Kindly log this detail in the jira ticket too for future reference.
2. Need to make Readme/UG update for this. I have inline (in comments) called out. Mainly for the new interactive/non-interactive option that we introduced for pre-build.

2021-11-29 06:01 UTC, aditisa1 commented on MQTT/Dockerfile
>  RUN apt-get update && apt-get install -y mosquitto mosquitto-clients
Shared the  excel for changes in image size in both the teams group created for this PR and to nagdeep in chat

2021-11-29 06:05 UTC, aditisa1 commented on build_scripts/02_provision_UWC.sh
> +    if [ ! -z "$pre_build" ]; then
yes ,  i have tested in non-interacive mode , it is working fine

2021-11-29 06:08 UTC, aditisa1 commented on build_scripts/03_Build_Run_UWC.sh
> +                docker-compose -f docker-compose-build.yml build ia_eiibase ia_common ia_telegraf emb_publisher
influxDB is present in opensource 
https://hub.docker.com/u/openedgeinsights

2021-11-29 06:08 UTC, aditisa1 commented on build_scripts/03_Build_Run_UWC.sh
> +                docker-compose -f docker-compose-build.yml build ia_eiibase ia_common ia_telegraf
influxDB is present in opensource
https://hub.docker.com/u/openedgeinsights

2021-11-29 06:11 UTC, aditisa1 commented
Replies for generic comments 
1.  I have done that , shared the results previously , attaching here too 
[multi_stage_mem.xlsx](https://github.com/open-edge-insights/uwc/files/7615911/multi_stage_mem.xlsx)

2. Sure after this PR gets merged , will do that

3.  Will sync with you to understand this better.

2021-11-29 08:28 UTC, vkb1 reviewed
Rest other changes looks good.

2021-11-29 08:28 UTC, vkb1 commented on MQTT/Dockerfile
>  FROM eiibase
yes, this is not needed here.

2021-11-29 08:28 UTC, vkb1 commented on MQTT/Dockerfile
>  RUN apt-get update && apt-get install -y mosquitto mosquitto-clients
apt-get update is needed on every RUN statement where we are doing apt-get install

2021-11-29 08:28 UTC, vkb1 commented on build_scripts/03_Build_Run_UWC.sh
> +    rm setenv
This file can be removed right after sourcing itself as there can some errors in between which can cause you to exit and not running this

2021-11-29 08:28 UTC, vkb1 commented on build_scripts/03_Build_Run_UWC.sh
> +        exit 1
This needs to be indented correctly inside else block. Same at line 103

2021-11-29 08:28 UTC, vkb1 commented on kpi-tactic/Dockerfile
> +COPY --from=uwc_common /usr/local/lib ${APP_WORK_DIR}
sorry to get back late on this, you can print and see the value of CMAKE_INSTALL_PREFIX. The value for this has to be `/usr/local` itself. If the value is not coming correctly here then this is not getting passed as a build arg like in EII

2021-11-29 09:03 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +    rm setenv
HI @vkb1 : We might need to maintain this file (Reason as mentioned in my previous comment in https://github.com/open-edge-insights/uwc/pull/34/files#r757084479).

2021-12-01 06:22 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +	# Checking if ia_telegraf has to be build or not.
Can rephrase to be accurate - "Checking if ia_telegraf has to be build or not." -> "Checking if ia_telegraf  is part of the recipe use case selected. ."
B'coz, telegraf is always supposed to be built if its selected in use case.

2021-12-01 06:22 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +        test_1=`grep "ia_telegraf" "docker-compose-build.yml"`
even on temporary variables, lets keep meaningful names, like "is_ia_telegraf_present" or somethign similiar. Same for test_2 also.

2021-12-01 06:22 UTC, nagdeepgk commented on build_scripts/03_Build_Run_UWC.sh
> +                docker-compose -f docker-compose-build.yml build ia_eiibase ia_common ia_telegraf emb_publisher
ok

2021-12-01 06:22 UTC, nagdeepgk commented
I don't see ReadMe updated.

2021-12-02 04:32 UTC, aditisa1 commented on build_scripts/03_Build_Run_UWC.sh
> +        exit 1
seeing the issue here , in actual file it is looks fine
https://github.com/open-edge-insights/uwc/blob/b15e38ea5057594f78bd5953a18361d77744535f/build_scripts/03_Build_Run_UWC.sh

2021-12-02 04:40 UTC, Kevin-Midkiff requested changes

2021-12-02 04:40 UTC, Kevin-Midkiff commented on MQTT/Dockerfile
>  RUN apt-get update && apt-get install -y mosquitto mosquitto-clients
@vkb1 recently pointed out to me in a different review that after all `apt-get update` commands after the install we should add `rm -rf /var/lib/apt/lists/*`. So I believe this should be:
```
RUN apt-get update && apt-get install -y mosquitto mosquitto-clients && rm -rf /var/lib/apt/lists/*
```

Also, do we really need the `mosquitto-clients` script? This is for launching the broker, right? Do we need all the client applications for that?

2021-12-02 04:40 UTC, Kevin-Midkiff commented on MQTT/docker-compose.yml
> +    image: ${DOCKER_REGISTRY}openedgeinsights/mqtt_container:${EII_VERSION}
Is this container for the MQTT broker? If so, we may want to change the container name. In general, I think we should avoid having "container" in a container name. How about something like: "ia_mqtt_broker"?

2021-12-02 04:40 UTC, Kevin-Midkiff commented on README.md
> +There are two ways in which the containers can be build either by using the opensource pre build images as present in [openedgeinsights](https://hub.docker.com/u/openedgeinsights) or by building imag
Are we referring to pulling the pre-built base images or pulling the UWC containers? We may want to make it a bit more clear. Also, I would change "pre build" to "pre-built".

2021-12-02 04:40 UTC, Kevin-Midkiff commented on build_scripts/02_provision_UWC.sh
> +            --pre_build)    pre_build=${VALUE} ;;
This should probably be `pre_built`. Also, I see that we are mixing camel case and snakecase in our arguments. I don't care which one we decide on, but let's aim for consistency. So `pre_built` should either change to `preBuilt` or `deployMode` should change to `deploy_mode`.

Although, I usually prefer to use dashes in command lines like this. Maybe something like `--pre-built` if you choose snakecase.

2021-12-02 04:40 UTC, Kevin-Midkiff commented on build_scripts/02_provision_UWC.sh
> +        #mv setenv ../../build/
Can this line be removed?

2021-12-02 04:40 UTC, Kevin-Midkiff commented on build_scripts/02_provision_UWC.sh
> +    echo "${INFO}--pre_build yes to use pre-build images else no to build images locally"
So is the aim here that from the command line I would do `--pre_build yes`? If so, I think it would be cleaner if this was treated as a flag, i.e. require the user to just put `--pre_build` (do not require the "yes" at the end).

2021-12-02 04:40 UTC, Kevin-Midkiff commented on build_scripts/03_Build_Run_UWC.sh
>          exit 1
Are we exiting with return code `1` even if we are successful? Or maybe this is part of the `else` block. If so, the indentation is incorrect and we should tab this in by one to make sure it is in the correct spot in the code.

2021-12-02 04:40 UTC, Kevin-Midkiff commented on kpi-tactic/Dockerfile
> +ARG CMAKE_INSTALL_PREFIX
Can we have a default value for this value? Maybe a bit easier to have a default value and a bit more clear for users.

2021-12-02 04:40 UTC, Kevin-Midkiff commented on modbus-master/Dockerfile
> +RUN echo "$CMAKE_INSTALL_PREFIX:build"
Do we need these echos?

2021-12-02 04:40 UTC, Kevin-Midkiff commented on modbus-master/Dockerfile
> +ARG CMAKE_INSTALL_PREFIX
Same default value question

2021-12-02 05:42 UTC, aditisa1 commented on MQTT/docker-compose.yml
> +    image: ${DOCKER_REGISTRY}openedgeinsights/mqtt_container:${EII_VERSION}
We can take this as a different story as this one is mostly about multi stage changes.

2021-12-02 05:44 UTC, aditisa1 commented on README.md
> +There are two ways in which the containers can be build either by using the opensource pre build images as present in [openedgeinsights](https://hub.docker.com/u/openedgeinsights) or by building imag
We are not only pulling UWC containers but also EII containers like influxdb , so kept is generic for now

2021-12-02 05:47 UTC, aditisa1 commented on kpi-tactic/Dockerfile
> +ARG CMAKE_INSTALL_PREFIX
Currently we have set the value of CMAKE_INSTALL_PREFIX in docker-compose.yml like following 

CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
https://github.com/open-edge-insights/uwc/blob/b15e38ea5057594f78bd5953a18361d77744535f/kpi-tactic/docker-compose.yml

2021-12-02 05:48 UTC, aditisa1 commented on modbus-master/Dockerfile
> +ARG CMAKE_INSTALL_PREFIX
Currently we have set the value of CMAKE_INSTALL_PREFIX in docker-compose.yml like following

CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
https://github.com/open-edge-insights/uwc/blob/b15e38ea5057594f78bd5953a18361d77744535f/kpi-tactic/docker-compose.yml

2021-12-02 05:53 UTC, vkb1 commented on MQTT/Dockerfile
>  ARG EII_VERSION
You may not need this EII_VERSION here and in compose file

2021-12-02 05:53 UTC, vkb1 commented on README.md
> +There are two ways in which the containers can be build either by using the opensource pre build images as present in [openedgeinsights](https://hub.docker.com/u/openedgeinsights) or by building imag
+1. I think @aditisa1 is referring to UWC docker images being published to docker hub which doesn't include uwc_common image

2021-12-02 05:53 UTC, vkb1 commented on README.md
> +$ sudo ./02_provision_UWC.sh --help
Let's not include $ here, we are making this change in EII 3.0

2021-12-02 05:53 UTC, vkb1 commented on build_scripts/02_provision_UWC.sh
> +            --pre_build)    pre_build=${VALUE} ;;
+1.

2021-12-02 05:53 UTC, vkb1 commented on build_scripts/03_Build_Run_UWC.sh
> +        exit 1
I see some indentation issues like https://github.com/open-edge-insights/uwc/blob/b15e38ea5057594f78bd5953a18361d77744535f/build_scripts/03_Build_Run_UWC.sh#L85

2021-12-02 05:53 UTC, vkb1 commented on kpi-tactic/Dockerfile
> +ARG CMAKE_INSTALL_PREFIX
Agree to this but since we have docker-compose as the front end to build and launch containers, I feel users can configure them there only instead of having the default value which would be only for readability and needs update in all dockerfiles.

2021-12-02 05:53 UTC, vkb1 commented on modbus-master/Dockerfile
> +RUN echo "$CMAKE_INSTALL_PREFIX:build"
These things can be avoided.

2021-12-02 05:59 UTC, aditisa1 commented on MQTT/Dockerfile
>  ARG EII_VERSION
Will be raising a different PR for fixing this issue

2021-12-02 06:07 UTC, aditisa1 commented on README.md
> +$ sudo ./02_provision_UWC.sh --help
We will be opening a different story for fixing this in all documents of UWC.

2021-12-02 06:09 UTC, aditisa1 commented on build_scripts/03_Build_Run_UWC.sh
> +        exit 1
Yeah 
noticed this will push changes in latest patch

2021-12-02 06:16 UTC, vkb1 approved these changes

2021-12-02 06:21 UTC, nagdeepgk approved these changes

2021-12-03 04:10 UTC, Kevin-Midkiff approved these changes

2022-01-12 16:45 UTC, nagdeepgk commented
closing this PR as this feature is already merged in another PR.

2022-01-12 16:45 UTC, closed without merging