UWC : Modified the tags of the containers
open-edge-insights/uwc pull request #38
Opened 2021-12-03 06:34 UTC by aditisa1

Earlier containers were referring to EII_VERSION tag modified it to
UWC_VERSION.

Signed-off-by: aditisa1 <aditi.saxena@intel.com>

2021-12-03 09:47 UTC, vkb1 requested changes
Rest all looks good.

2021-12-03 09:47 UTC, vkb1 commented on modbus-master/modbus_RTU/docker-compose.yml
>          EII_VERSION: ${EII_VERSION}
You can remove EII_VERSION in Dockerfile and compose.yml files as you don't need them.

2021-12-03 09:51 UTC, aditisa1 commented on modbus-master/modbus_RTU/docker-compose.yml
>          EII_VERSION: ${EII_VERSION}
Hi Vinod,
EII_VERSION is being used in Dockerfile for ia_common 
https://github.com/open-edge-insights/uwc/blob/cacbbd0e76a54a43d8e6cb6d14c7f124996a617c/modbus-master/Dockerfile_RTU

2021-12-03 10:42 UTC, vkb1 approved these changes

2021-12-03 12:39 UTC, nagdeepgk commented
@aditisa1 https://github.com/open-edge-insights/uwc/blob/master/docker-compose_UT.yml UT files also needs to be updated from EII_VERSION to UWC_VERSION.

2021-12-06 07:32 UTC, nagdeepgk approved these changes

2021-12-06 07:37 UTC, merged