README: Modified for RT patch
open-edge-insights/uwc pull request #9
Opened 2021-08-11 14:41 UTC by aditisa1

Added notes and links for RT patch.

Signed-off-by: aditi saxena <aditi.saxena@intel.com>

2021-08-12 16:33 UTC, aditisa1 commented
@vanidesai can you please review the MR

2021-08-13 06:52 UTC, vanidesai requested changes

2021-08-13 06:52 UTC, vanidesai commented on README.md
> +  * Please go through the links https://mirrors.edge.kernel.org/pub/linux/kernel/ or https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/ to find the exact RT Patch for your system and insta
Please point to UWC userguide location that points to RT patch installation.

2021-08-13 09:14 UTC, vkb1 commented on README.md
> +  * If user wants to install RT_patch they need to disable secure root as per limitation of ubuntu.
Did you mean `secure boot` instead of `secure root`?

2021-08-13 09:14 UTC, vkb1 commented on README.md
> +  * Please go through the links https://mirrors.edge.kernel.org/pub/linux/kernel/ or https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/ to find the exact RT Patch for your system and insta
+1

2021-08-13 12:53 UTC, aditisa1 commented on README.md
> +  * Please go through the links https://mirrors.edge.kernel.org/pub/linux/kernel/ or https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/ to find the exact RT Patch for your system and insta
Hi 
Currently in uwc-docs repo still has the older 18.04 way of getting RT patch , We are waiting for the Sphinx issues to resolve after that the User guide will be updated.
It is planned to make these Sphinx fixes after the RC1 release and before UWC-1.6 PV tag. So we can make this change in README post RC1 tag.

2021-08-16 06:20 UTC, vanidesai approved these changes

2021-08-16 12:04 UTC, nagdeepgk approved these changes

2021-08-16 12:04 UTC, nagdeepgk commented on README.md
> +  * Please go through the links https://mirrors.edge.kernel.org/pub/linux/kernel/ or https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/ to find the exact RT Patch for your system and insta
Yes as Aditi mentioned, we can update user-guide only after fixing sphinx issues. Hence, to not lose track of this, I've created a story and added in next sprint so that we pick it up once sphinx issues addressed.
https://jira.devtools.intel.com/browse/IAPOC9-9535 .

Going ahead with merge with this.

2021-08-16 12:05 UTC, merged